version: "3.9"
volumes:
  postgres_data:

services:
  postgres:
    container_name: ucrm-go-db
    image: postgres:11.13-alpine
    command:
      - "postgres"
      - "-c"
      - "max_connections=50"
      - "-c"
      - "shared_buffers=1GB"
      - "-c"
      - "effective_cache_size=4GB"
      - "-c"
      - "work_mem=16MB"
      - "-c"
      - "maintenance_work_mem=512MB"
      - "-c"
      - "random_page_cost=1.1"
      - "-c"
      - "temp_file_limit=10GB"
      - "-c"
      - "log_min_duration_statement=200ms"
      - "-c"
      - "idle_in_transaction_session_timeout=10s"
      - "-c"
      - "lock_timeout=1s"
      - "-c"
      - "statement_timeout=60s"
      - "-c"
      - "shared_preload_libraries=pg_stat_statements"
      - "-c"
      - "pg_stat_statements.max=10000"
      - "-c"
      - "pg_stat_statements.track=all"
    environment:
      POSTGRES_DB: ${DATABASE_NAME:-ucrm-db}
      POSTGRES_USER: ${DATABASE_USER:-user}
      POSTGRES_PASSWORD: ${DATABASE_PASS:-pass}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql/migrations:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${DATABASE_USER:-user} -d ${DATABASE_NAME:-ucrm-db}",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 4G
    networks:
      ucrm:
        ipv4_address: 172.4.4.3
        aliases:
          - ucrm.db.loc
  app:
    depends_on:
      - postgres
    links:
      - postgres
    build:
      context: ./
      dockerfile: docker/develop/app.Dockerfile
    env_file:
      - .env
    image: app:docker
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_PTRACE
    ports:
      - 8080:8080
      - 2345:2345
    entrypoint: 
      ['/dlv', '--listen=:2345', '--headless=true', '--api-version=2', '--accept-multiclient', 'exec', '/usr/local/bin/app/main']
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "100M"
        reservations:
          cpus: "0.25"
          memory: 30M
    networks:
      ucrm:
        ipv4_address: 172.4.4.2
        aliases:
          - ucrm.api.loc
networks:
  ucrm:
    name: ucrm
    ipam:
      config:
        - subnet: "172.4.4.0/24"
