cors:
  allow_credentials: false
  allowed_headers:
    - '*'
  allowed_methods:
    - 'GET'
    - 'POST'
    - 'OPTIONS'
    - 'HEAD'
    - 'PATCH'
    - 'PUT'
  allowed_origins:
    - '*'
  debug_cors: false
  exposed_headers:
    - '*'
  # 10 m
  max_age: 600
  options_passthrough: false
  use_allow_all_handler: true

mail:
  sender: 'ucrm@info.com'
  letters:
    verification:
      subject: 'Verification Code'
      template: 'your verification code {{ .Data.Code }}, enter it within 5 minutes'
