definitions:
  models.Card:
    properties:
      chat:
        $ref: '#/definitions/models.Chat'
      contacts:
        items:
          $ref: '#/definitions/models.Contact'
        type: array
      fields:
        items:
          $ref: '#/definitions/models.CardField'
        type: array
      id:
        type: string
      name:
        type: string
      order:
        type: integer
      pipeline_id:
        type: string
      updated_at:
        type: string
    type: object
  models.CardField:
    properties:
      card_id:
        type: string
      dashboard_id:
        type: string
      field_id:
        type: string
      id:
        type: string
      is_nullable:
        type: boolean
      name:
        type: string
      type:
        type: string
      value:
        type: string
    type: object
  models.Chat:
    properties:
      card_id:
        type: string
      id:
        type: string
      last_employee_id:
        type: string
      last_message:
        type: string
      last_sender:
        type: string
    type: object
  models.Contact:
    properties:
      card_id:
        type: string
      city:
        type: string
      dashboard_id:
        type: string
      fields:
        items:
          $ref: '#/definitions/models.ContactField'
        type: array
      id:
        type: string
      name:
        type: string
      phone:
        type: string
    type: object
  models.ContactField:
    properties:
      contact_id:
        type: string
      dashboard_id:
        type: string
      field_id:
        type: string
      id:
        type: string
      is_nullable:
        type: boolean
      name:
        type: string
      type:
        type: string
      value:
        type: string
    type: object
info:
  contact: {}
  description: Unnamed URCM
  title: Unnamed URCM
  version: "1.0"
paths:
  /cards:
    delete:
      parameters:
      - description: ' '
        in: query
        name: id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Card'
      summary: Delete card
      tags:
      - cards
    patch:
      parameters:
      - description: ' '
        in: query
        name: cardId
        required: true
        type: string
      responses:
        "200":
          description: ""
      summary: Update card
      tags:
      - cards
    post:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Card'
        "400":
          description: '[CreateOne]: {error}'
          schema:
            type: string
        "500":
          description: '[CreateOne]: {error}'
          schema:
            type: string
      summary: Create card
      tags:
      - cards
  /cards/{cardId}:
    get:
      description: Get one card by id
      parameters:
      - description: ' '
        in: query
        name: cardId
        required: true
        type: string
      responses:
        "200":
          description: ""
      summary: Get one card
      tags:
      - cards
  /cards/order/{pipelineId}/{cardId}/order:
    get:
      description: Update order
      parameters:
      - description: ' '
        in: query
        name: cardId
        required: true
        type: string
      - description: ' '
        in: query
        name: pipelineId
        required: true
        type: string
      - description: ' '
        in: query
        name: order
        required: true
        type: string
      responses:
        "200":
          description: ""
      summary: Update order
      tags:
      - cards
  /connect/create:
    post:
      description: Create queue
      responses:
        "200":
          description: ""
      summary: Create queue
      tags:
      - connect
  /connect/ping:
    post:
      description: Create queue
      responses:
        "200":
          description: ""
      summary: Create queue
      tags:
      - connect
  /connect/unsubscribe:
    post:
      responses:
        "200":
          description: ""
      summary: Unsubscribe
      tags:
      - connect
  /contacts/{cardId}:
    delete:
      responses:
        "200":
          description: ""
      summary: Unsubscribe
      tags:
      - contacts
swagger: "2.0"
